import url from './config';

module.exports = {
  'Create document': (browser) => {
    browser
      .url(url.login)
      .waitForElementVisible('body')
      .assert.containsText('div', 'Welcome to Doc-mgt.')
      .pause(5000)
      .assert.elementPresent('input[id=loginID]')
      .setValue('input[id=loginID]', 'obinna@obinna.com')
      .setValue('input[id=password]', 'obinna')
      .click('button')
      .pause(2000)
      .assert.urlContains('dashboard')
      .assert.elementPresent('.side-bar')
      .click('#users')
      .pause(2000)
      .click('#mode-edit')
      .setValue('input[id="firstName"]', 'Alan')
      .setValue('#roleID', '2')
      .pause(2000)
      .click('button')
      .pause(2000)
      // .assert.urlContains('documents')
      // .click('#mydocument')
      // .pause(1000)
      // .assert.urlContains('mydocument')
      // .click('#viewdoc')
      // .pause(1000)
      // .assert.urlContains('document')
      // .assert.elementPresent('#doc-title')
      // .pause(1000)
      // .click('#edit-doc')
      // .pause(1000)
      // .execute('CKEDITOR.instances.content.setData("My Content is updted")')
      // .pause(1000)
      // .click('select[id=access] option[value=private]')
      // .pause(1000)
      // .click('button')
      // .pause(1000)
      // .click('#delete-doc')
      // .pause(1000)
      // .click('.confirm')
      // .pause(2000)
      // .click('.confirm')
      // .pause(2000)
      // .click('#logout')
      // .pause(3000)
      // .assert.containsText('div', 'Welcome to Doc-mgt.')
      .pause(1000)
      .end();
  }
};
