export default {
  LOGIN_DETAILS: 'LOGIN_DETAILS',
  SIGNUP_DETAILS: 'SIGNUP_DETAILS',
  ADD_DOCUMENT: 'ADD_DOCUMENT',
  GET_DOCUMENTS: 'GET_DOCUMENTS',
  DELETE_DOCUMENT: 'DELETE_DOCUMENT',
  GET_SINGLE_DOCUMENT: 'GET_SINGLE_DOCUMENT',
  UPDATE_DOCUMENT: 'UPDATE_DOCUMENT',
  GET_USERS: 'GET_USERS',
  DELETE_USER: 'DELETE_USER',

};
