export default {
  LOGIN_DETAILS: 'LOGIN_DETAILS',
  SIGNUP_DETAILS: 'SIGNUP_DETAILS',
  ADD_DOCUMENTS: 'ADD_DOCUMENTS',
  GET_DOCUMENTS: 'GET_DOCUMENTS',
  DELETE_DOCUMENTS: 'DELETE_DOCUMENTS',
  GET_SINGLE_DOCUMENTS: 'GET_SINGLE_DOCUMENTS',


};
