export default {
  LOGIN_DETAILS: 'LOGIN_DETAILS',
  LOG_OUT: 'LOG_OUT',
  SIGNUP_DETAILS: 'SIGNUP_DETAILS',
  ADD_DOCUMENT: 'ADD_DOCUMENT',
  GET_DOCUMENTS: 'GET_DOCUMENTS',
  GET_MY_DOCUMENTS: 'GET_MY_DOCUMENTS',
  DELETE_DOCUMENT: 'DELETE_DOCUMENT',
  GET_SINGLE_DOCUMENT: 'GET_SINGLE_DOCUMENT',
  UPDATE_DOCUMENT: 'UPDATE_DOCUMENT',
  GET_USERS: 'GET_USERS',
  DELETE_USER: 'DELETE_USER',
  UPDATE_USER: 'UPDATE_USER',
  GET_SINGLE_USER: 'GET_SINGLE_USER',
  SEARCH_DOCUMENTS: 'SEARCH_DOCUMENTS',
  SEARCH_USERS: 'SEARCH_USERS',


};
